/*
 * ADPSS Wrapper for Simulink-generated model: testadpssmodel260402
 *
 * Auto-generated by generate_adpss_wrapper.py
 * Source: testadpssmodel260402_ert_shrlib_rtw/testadpssmodel260402.h
 *
 * Model I/O: 3 input(s), 2 output(s)
 */

#include <stdlib.h>
#include <string.h>
#include "testadpssmodel260402.h"

#ifdef _WINDOWS
#ifdef _DLLAPI
#define DLLAPI __declspec(dllexport)
#else
#define DLLAPI __declspec(dllimport)
#endif
#else
#define DLLAPI
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Model instance struct for pModelInfo */
typedef struct {
    int initialized;
} AdpssModelInstance;

/*
 * Inittestadpssmodel260402 - ADPSS initialization interface
 * Returns 0 on success, non-zero on error.
 */
int DLLAPI Inittestadpssmodel260402(
    void **pModelInfo,
    int Parameter_N,
    int Nin,
    int Nout,
    double *Parameter,
    double *Val_In,
    double *Val_out,
    int Store_Size,
    char *Store_Add,
    double Tnow,
    double DT)
{
    AdpssModelInstance *inst;

    inst = (AdpssModelInstance *)malloc(sizeof(AdpssModelInstance));
    if (inst == NULL) {
        return -1;
    }

    testadpssmodel260402_initialize();
    inst->initialized = 1;
    *pModelInfo = (void *)inst;

    /* Copy inputs from ADPSS to Simulink */
    if (Nin > 0 && Val_In != NULL) {
        testadpssmodel260402_U.Vabc[0] = Val_In[0];
        testadpssmodel260402_U.Vabc[1] = Val_In[1];
        testadpssmodel260402_U.Vabc[2] = Val_In[2];
    }

    testadpssmodel260402_step();

    /* Copy outputs from Simulink to ADPSS */
    if (Nout > 0 && Val_out != NULL) {
        Val_out[0] = testadpssmodel260402_Y.theta;
        Val_out[1] = testadpssmodel260402_Y.Va;
    }

    return 0;
}

/*
 * Steptestadpssmodel260402 - ADPSS simulation step interface
 * Returns 0 on success, non-zero on error.
 */
int DLLAPI Steptestadpssmodel260402(
    void *pModelInfo,
    int Mark,
    double *Val_In,
    double *Val_Out,
    char *Store_Add,
    double Tnow)
{
    (void)pModelInfo;
    (void)Mark;
    (void)Store_Add;
    (void)Tnow;

    /* Copy inputs from ADPSS to Simulink */
    if (Val_In != NULL) {
        testadpssmodel260402_U.Vabc[0] = Val_In[0];
        testadpssmodel260402_U.Vabc[1] = Val_In[1];
        testadpssmodel260402_U.Vabc[2] = Val_In[2];
    }

    testadpssmodel260402_step();

    /* Copy outputs from Simulink to ADPSS */
    if (Val_Out != NULL) {
        Val_Out[0] = testadpssmodel260402_Y.theta;
        Val_Out[1] = testadpssmodel260402_Y.Va;
    }

    return 0;
}

/*
 * Terminatetestadpssmodel260402 - ADPSS termination interface
 */
void DLLAPI Terminatetestadpssmodel260402(void *pModelInfo)
{
    testadpssmodel260402_terminate();

    if (pModelInfo != NULL) {
        free(pModelInfo);
    }
}

#ifdef __cplusplus
}
#endif
