#!/usr/bin/env python3
"""
Generate ADPSS wrapper files from Simulink-generated C code.

Parses the model header file to extract model name, inputs, and outputs,
then generates:
  - adpss_wrapper.c   (ADPSS <-> Simulink bridge)
  - CMakeLists.txt     (build configuration)

Usage:
  python generate_adpss_wrapper.py [model_code_dir]

If model_code_dir is omitted, auto-detects *_ert_shrlib_rtw/ in current dir.
"""

import os
import re
import sys
import glob


def find_model_dir():
    """Auto-detect the Simulink generated code directory."""
    candidates = glob.glob("*_ert_shrlib_rtw")
    dirs = [c for c in candidates if os.path.isdir(c)]
    if len(dirs) == 1:
        return dirs[0]
    elif len(dirs) == 0:
        print("Error: No *_ert_shrlib_rtw directory found. "
              "Specify the path as argument.")
        sys.exit(1)
    else:
        print(f"Error: Multiple candidates found: {dirs}. "
              "Specify one as argument.")
        sys.exit(1)


def extract_model_name(model_dir):
    """Extract model name from the directory name."""
    dirname = os.path.basename(model_dir.rstrip("/\\"))
    # Remove _ert_shrlib_rtw suffix
    suffix = "_ert_shrlib_rtw"
    if dirname.endswith(suffix):
        return dirname[:-len(suffix)]
    print(f"Error: Directory '{dirname}' does not end with {suffix}")
    sys.exit(1)


def parse_struct_fields(header_text, struct_type_prefix, model_name):
    """
    Parse fields from a typedef struct in the header.

    Looks for pattern:
      typedef struct {
        real_T FieldName;          /* comment */
        int32_T Field2[3];         /* comment */
      } ExtU_modelname_T;

    Returns list of (c_type, field_name, array_size_or_None).
    """
    # Match the full struct block
    type_name = f"{struct_type_prefix}_{model_name}_T"
    pattern = (
        r"typedef\s+struct\s*\{([^}]*)\}\s*"
        + re.escape(type_name)
        + r"\s*;"
    )
    match = re.search(pattern, header_text, re.DOTALL)
    if not match:
        return []

    body = match.group(1)
    fields = []

    # Match each field: type name; or type name[N];
    field_pattern = r"(\w+)\s+(\w+)(?:\[(\d+)\])?\s*;"
    for m in re.finditer(field_pattern, body):
        c_type = m.group(1)
        name = m.group(2)
        array_size = int(m.group(3)) if m.group(3) else None
        fields.append((c_type, name, array_size))

    return fields


def field_count(fields):
    """Total number of double slots needed for all fields."""
    total = 0
    for _, _, arr_size in fields:
        total += arr_size if arr_size else 1
    return total


# Types that are already double-compatible (no cast needed)
DOUBLE_TYPES = {"real_T", "real64_T", "time_T"}


def generate_wrapper_c(model_name, model_dir, inputs, outputs):
    """Generate adpss_wrapper.c content."""
    nin = field_count(inputs)
    nout = field_count(outputs)
    dir_basename = os.path.basename(model_dir.rstrip("/\\"))

    lines = []
    lines.append(f"""\
/*
 * ADPSS Wrapper for Simulink-generated model: {model_name}
 *
 * Auto-generated by generate_adpss_wrapper.py
 * Source: {dir_basename}/{model_name}.h
 *
 * Model I/O: {nin} input(s), {nout} output(s)
 */

#include <stdlib.h>
#include <string.h>
#include "{model_name}.h"

#ifdef _WINDOWS
#ifdef _DLLAPI
#define DLLAPI __declspec(dllexport)
#else
#define DLLAPI __declspec(dllimport)
#endif
#else
#define DLLAPI
#endif

#ifdef __cplusplus
extern "C" {{
#endif

/* Model instance struct for pModelInfo */
typedef struct {{
    int initialized;
}} AdpssModelInstance;
""")

    # --- Init function ---
    lines.append(f"""\
/*
 * Init{model_name} - ADPSS initialization interface
 * Returns 0 on success, non-zero on error.
 */
int DLLAPI Init{model_name}(
    void **pModelInfo,
    int Parameter_N,
    int Nin,
    int Nout,
    double *Parameter,
    double *Val_In,
    double *Val_out,
    int Store_Size,
    char *Store_Add,
    double Tnow,
    double DT)
{{
    AdpssModelInstance *inst;

    inst = (AdpssModelInstance *)malloc(sizeof(AdpssModelInstance));
    if (inst == NULL) {{
        return -1;
    }}

    {model_name}_initialize();
    inst->initialized = 1;
    *pModelInfo = (void *)inst;

    /* Copy inputs from ADPSS to Simulink */
    if (Nin > 0 && Val_In != NULL) {{""")

    idx = 0
    for c_type, name, arr_size in inputs:
        if arr_size:
            for i in range(arr_size):
                cast = "" if c_type in DOUBLE_TYPES else f"({c_type})"
                lines.append(
                    f"        {model_name}_U.{name}[{i}] = "
                    f"{cast}Val_In[{idx}];")
                idx += 1
        else:
            cast = "" if c_type in DOUBLE_TYPES else f"({c_type})"
            lines.append(
                f"        {model_name}_U.{name} = "
                f"{cast}Val_In[{idx}];")
            idx += 1

    lines.append(f"""\
    }}

    {model_name}_step();

    /* Copy outputs from Simulink to ADPSS */
    if (Nout > 0 && Val_out != NULL) {{""")

    idx = 0
    for c_type, name, arr_size in outputs:
        if arr_size:
            for i in range(arr_size):
                cast = "" if c_type in DOUBLE_TYPES else "(double)"
                lines.append(
                    f"        Val_out[{idx}] = "
                    f"{cast}{model_name}_Y.{name}[{i}];")
                idx += 1
        else:
            cast = "" if c_type in DOUBLE_TYPES else "(double)"
            lines.append(
                f"        Val_out[{idx}] = "
                f"{cast}{model_name}_Y.{name};")
            idx += 1

    lines.append("""\
    }

    return 0;
}
""")

    # --- Step function ---
    lines.append(f"""\
/*
 * Step{model_name} - ADPSS simulation step interface
 * Returns 0 on success, non-zero on error.
 */
int DLLAPI Step{model_name}(
    void *pModelInfo,
    int Mark,
    double *Val_In,
    double *Val_Out,
    char *Store_Add,
    double Tnow)
{{
    (void)pModelInfo;
    (void)Mark;
    (void)Store_Add;
    (void)Tnow;

    /* Copy inputs from ADPSS to Simulink */
    if (Val_In != NULL) {{""")

    idx = 0
    for c_type, name, arr_size in inputs:
        if arr_size:
            for i in range(arr_size):
                cast = "" if c_type in DOUBLE_TYPES else f"({c_type})"
                lines.append(
                    f"        {model_name}_U.{name}[{i}] = "
                    f"{cast}Val_In[{idx}];")
                idx += 1
        else:
            cast = "" if c_type in DOUBLE_TYPES else f"({c_type})"
            lines.append(
                f"        {model_name}_U.{name} = "
                f"{cast}Val_In[{idx}];")
            idx += 1

    lines.append(f"""\
    }}

    {model_name}_step();

    /* Copy outputs from Simulink to ADPSS */
    if (Val_Out != NULL) {{""")

    idx = 0
    for c_type, name, arr_size in outputs:
        if arr_size:
            for i in range(arr_size):
                cast = "" if c_type in DOUBLE_TYPES else "(double)"
                lines.append(
                    f"        Val_Out[{idx}] = "
                    f"{cast}{model_name}_Y.{name}[{i}];")
                idx += 1
        else:
            cast = "" if c_type in DOUBLE_TYPES else "(double)"
            lines.append(
                f"        Val_Out[{idx}] = "
                f"{cast}{model_name}_Y.{name};")
            idx += 1

    lines.append("""\
    }

    return 0;
}
""")

    # --- Terminate function ---
    lines.append(f"""\
/*
 * Terminate{model_name} - ADPSS termination interface
 */
void DLLAPI Terminate{model_name}(void *pModelInfo)
{{
    {model_name}_terminate();

    if (pModelInfo != NULL) {{
        free(pModelInfo);
    }}
}}

#ifdef __cplusplus
}}
#endif
""")

    return "\n".join(lines)


def generate_cmake(model_name, model_dir):
    """Generate CMakeLists.txt content."""
    dir_basename = os.path.basename(model_dir.rstrip("/\\"))

    # Find all .c files in model_dir (excluding ert_main.c)
    c_files = sorted(glob.glob(os.path.join(model_dir, "*.c")))
    c_files = [f for f in c_files
               if os.path.basename(f) != "ert_main.c"]
    sources_list = "\n    ".join(
        f"${{MODEL_DIR}}/{os.path.basename(f)}" for f in c_files
    )

    return f"""\
cmake_minimum_required(VERSION 3.15)
project(adpss_{model_name} C)

set(MODEL_DIR ${{CMAKE_SOURCE_DIR}}/{dir_basename})

add_library(adpss_{model_name} SHARED
    adpss_wrapper.c
    {sources_list}
)

target_include_directories(adpss_{model_name} PRIVATE
    ${{MODEL_DIR}}
)

target_compile_definitions(adpss_{model_name} PRIVATE
    _WINDOWS
    _DLLAPI
    _MBCS
    MODEL={model_name}
    NUMST=1
    NCSTATES=0
    CLASSIC_INTERFACE=0
    ALLOCATIONFCN=0
    TERMFCN=1
    ONESTEPFCN=1
    MAT_FILE=0
    MULTI_INSTANCE_CODE=0
    INTEGER_CODE=0
    MT=0
    TID01EQ=0
)

# MSVC: static runtime (/MT), match VS2012 flags
if(MSVC)
    set_property(TARGET adpss_{model_name} PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded")
    target_compile_options(adpss_{model_name} PRIVATE
        /W3 /GS /Gy /Gd /Oi /GL /EHsc
    )
    target_link_options(adpss_{model_name} PRIVATE
        /LTCG
    )
endif()

# MinGW: static link runtime (for local builds)
if(MINGW)
    target_link_options(adpss_{model_name} PRIVATE -static-libgcc -static -m32)
    target_compile_options(adpss_{model_name} PRIVATE -m32)
endif()

set_target_properties(adpss_{model_name} PROPERTIES
    PREFIX ""
    OUTPUT_NAME "adpss_{model_name}"
)
"""


def main():
    # Determine model directory
    if len(sys.argv) > 1:
        model_dir = sys.argv[1]
    else:
        model_dir = find_model_dir()

    if not os.path.isdir(model_dir):
        print(f"Error: '{model_dir}' is not a directory")
        sys.exit(1)

    model_name = extract_model_name(model_dir)
    header_path = os.path.join(model_dir, f"{model_name}.h")

    if not os.path.isfile(header_path):
        print(f"Error: Header file not found: {header_path}")
        sys.exit(1)

    with open(header_path, "r") as f:
        header_text = f.read()

    # Parse inputs and outputs
    inputs = parse_struct_fields(header_text, "ExtU", model_name)
    outputs = parse_struct_fields(header_text, "ExtY", model_name)

    print(f"Model:   {model_name}")
    print(f"Inputs:  {len(inputs)} field(s), "
          f"{field_count(inputs)} double slot(s)")
    for t, n, a in inputs:
        sz = f"[{a}]" if a else ""
        print(f"  - {t} {n}{sz}")
    print(f"Outputs: {len(outputs)} field(s), "
          f"{field_count(outputs)} double slot(s)")
    for t, n, a in outputs:
        sz = f"[{a}]" if a else ""
        print(f"  - {t} {n}{sz}")

    # Generate files
    wrapper_c = generate_wrapper_c(model_name, model_dir, inputs, outputs)
    cmake = generate_cmake(model_name, model_dir)

    # Write output files
    with open("adpss_wrapper.c", "w") as f:
        f.write(wrapper_c)
    print("\nGenerated: adpss_wrapper.c")

    with open("CMakeLists.txt", "w") as f:
        f.write(cmake)
    print("Generated: CMakeLists.txt")

    print(f"\nDone! Build with:")
    print(f'  cmake -B build -G "MinGW Makefiles"')
    print(f"  cmake --build build")
    print(f"\nOutput DLL: build/adpss_{model_name}.dll")


if __name__ == "__main__":
    main()
